spring:
  application:
    name: trading-app
  
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: app
    password: password
    driver-class-name: oracle.jdbc.OracleDriver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
    database-platform: org.hibernate.dialect.OracleDialect
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

server:
  port: 8080

logging:
  level:
    com.example.tradingapp: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 